### PR TITLE
refactor: update intro

### PR DESCRIPTION
**Pull request by tplooker**
Looking for early review, still needs quite a bit of work

### CODE REVIEW

**Comment by tplooker** [comment]
ping @AdamJLemmon

**Comment by AdamJLemmon** [comment]
Looking great to me! Shared a couple small suggestions on grammar mainly.

**Comment by tplooker** [comment]
@AdamJLemmon happy to merge or want to review some more?

**Comment by AdamJLemmon** [comment]
Ship it! :)

**Pull request merged**
